name: Run Benchmarks (Linux)

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  schedule:
    # Every day at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  linux-build:
    name: Run Benchmarks on Linux (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Build the Benchmarks
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DUSING_GITHUB_ACTIONS=ON
          cmake --build . --config Release

      - name: Run Benchmark
        run: |
          cd build
          ls
          ./BenchmarksCPP

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v2
        with:
          name: arithmeticResults
          path: build/arithmeticResults.txt
