name: Run Benchmarks (Linux)

on:
  push:
      branches:
      - master
  pull_request:
      branches:
      - master
  schedule:
    # Every day at 00:00
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  linux-build:
    name: Run Benchmarks on Linux (ubuntu-latest)
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: recursive
          ref: ${{ steps.extract_branch.outputs.branch }}

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - name: Update Libraries
        continue-on-error: true
        run: |
          cd lib
          cd librapid
          git checkout master
          git pull

      - name: Build the Benchmarks
        run: |
          mkdir build
          cd build
          cmake .. -DUSING_GITHUB_ACTIONS=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_STANDARD=17 -DLIBRAPID_GET_BLAS=on -DLIBRAPID_USE_MULTIPREC=on
          cmake --build . --config Release
        env:
          CC: gcc-11
          CXX: g++-11          

      - name: Run Benchmark
        run: |
          cd build
          ls
          ./BenchmarksCPP

      - name: Push Changes
        continue-on-error: true
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@users.noreply.github.com"
          
          git add -A
          git commit -m "Update GitHub Actions Benchmark Results"
          git push origin master

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v2
        with:
          name: arithmeticResults
          path: build/arithmeticResults.txt
